module.exports = [
  'Biography',
  'Memoir',
  'Autobiographical novel',
  'Bildungsroman',
  'Slave narrative',
  'Contemporary slave narrative',
  'Neo-slave narrative',
  'Spiritual autobiography',
  'Creative nonfiction',
  'Diaries and Journals',
  'Erotic literature',
  'Essay, Treatise',
  'Fable, Fairy tale, Folklore',
  'History',
  'Popular history',
  'People\'s history',
  'Official history',
  'Academic history',
  'Narrative history',
  'Whig history',
  'Popular nonfiction',
  'Letter',
  'Religious text',
  'Apocalyptic',
  'Apocrypha',
  'Apologetics',
  'Autograph',
  'Autobiography',
  'Blessing',
  'Canon',
  'Chant',
  'Commentary',
  'Confession',
  'Covenant',
  'Creed',
  'Critique',
  'Canonical Criticism',
  'Form Criticism',
  'Higher Criticism',
  'Historical Criticism',
  'Lower Criticism',
  'Narrative Criticism',
  'Postmodern Criticism',
  'Psychological Criticism',
  'Redaction Criticism',
  'Rhetorical Criticism',
  'Socio-scientific Criticism',
  'Source Criticism',
  'Textual Criticism',
  'Cult Literature',
  'Curse',
  'Didactic',
  'Dialetic',
  'Rabbinic',
  'Aporiaic',
  'Elenctic',
  'Epistle',
  'Pauline Epistle',
  'General Epistle',
  'Encyclical',
  'Gospel',
  'Homily',
  'Narrative',
  'Genealogy',
  'Royal',
  'Prophetic',
  'Koan',
  'Lament',
  'Law',
  'Ceremonial',
  'Family',
  'Levitical',
  'Moral',
  'Natural',
  'Royal Decree',
  'Social',
  'Lectionary',
  'Liturgy',
  'Manuscript',
  'Morality Play',
  'Mysticism',
  'Erotic',
  'Historical',
  'Horror',
  'Pilgrim',
  'Mystery',
  'Redemption Story',
  'Occult Literature',
  'Origin Story',
  'Parable',
  'Prayer',
  'Poetry',
  'Philosophy',
  'Philosophical Theology',
  'Philosophy of Religion',
  'Metaphysics',
  'Religious Epistemology',
  'Hebrew Poetry',
  'Prophecy',
  'Blessing/Curse',
  'Messianic Prophecy',
  'Divinitory',
  'Oracle',
  'Woe Oracle',
  'Predictive',
  'Typology',
  'Vision',
  'Proverbs',
  'Psalms',
  'Imprecatory Psalm',
  'Pilgrim Song',
  'Praise',
  'Royal Psalm',
  'Thanksgiving',
  'Wisdom Psalm',
  'Revelation',
  'Natural Revelation',
  'Special Revelation',
  'Scientific writing',
  'Scripture',
  'Sutra',
  'Song',
  'Dirge',
  'Hymn',
  'Testament',
  'Theology',
  'Apologetic Theology',
  'Bibliology',
  'Biblical Theology',
  'Cosmology',
  'Christology',
  'Ecclesiology',
  'Eschatology',
  'Hamartiology',
  'Pneumatology',
  'Prolegomena',
  'Mariology',
  'Natural Theology',
  'Soteriology',
  'Theology Proper',
  'Theo-mythology',
  'True crime',
  'Wisdom Literature',
  'Woe',
  'Buddhist texts',
  'Lotus Sutra',
  'Tripitaka',
  'Christian literature',
  'New Testament',
  'Old Testament',
  'Patristic',
  'Anti-Nicene',
  'Post-Nicene',
  'Pseudepigripha',
  'Hindu Literature',
  'Vedas',
  'Bhagavad Gita',
  'Islamic literature',
  'Quran',
  'Haddith',
  'Jewish Literature',
  'Torah',
  'Nevi\'im',
  'Ketuvim',
  'Talmud',
  'Kabala',
  'Occult',
  'Incantation',
  'Spell'
];
